Fix Gradle 7.0 issues
OpenLiberty/ci.gradle pull request #595
Opened 2021-04-23 20:43 UTC by mattbsox

- Fixed issues when running the plugin with Gradle 7.0
- Updated the Gradle wrapper to the latest Gradle 6.X version: 6.8.3
- Updated Spring Boot plugin version to 2.4.3 from 2.0.4 in the Spring Boot 2.0 tests
- DevTest and PollingDevTest failing when run on Gradle 7.0. Underlying issue seems to be an AbstractMethodError when trying to access ServerExtension properties during project/task configuration. The `libertyDev` task seems to work properly when run outside of the test files.

The current version of the Spring Boot plugin used in the Spring Boot 2.0 tests requires Gradle 5 (5.6.x only) or Gradle 6 (6.3 or later)

Fixes #592

2021-04-23 20:56 UTC, cherylking requested changes

2021-04-23 20:56 UTC, cherylking commented on src/test/resources/arquillian-tests/skipWithXmlManaged/build.gradle
> +    implementation 'io.openliberty.arquillian:arquillian-liberty-managed:1.0.6'
I just released 1.0.7 today. So might as well update these now.

2021-04-23 20:56 UTC, cherylking commented on src/main/groovy/io/openliberty/tools/gradle/LibertyTasks.groovy
> +            if (dependsOnApps(project.liberty.server)) {
General comment to update the copyright year in all the groovy files you updated.

2021-04-23 21:18 UTC, cherylking approved these changes

2021-04-27 13:09 UTC, cherylking commented
I like the test case fix. Did you see the new issue opened about the Windows builds failing with the idea of running gradle clean task at end of integration tests? Would that be worth a try?

2021-04-27 15:16 UTC, mattbsox commented
Yeah, that makes sense. I'll see if there is a good way to tie that to CI builds with a flag somewhere. I'd only like to do that when necessary.

2021-04-28 16:23 UTC, merged