Add installDir project property detection
OpenLiberty/ci.gradle pull request #651
Opened 2021-11-18 15:56 UTC by dshimo

for issue #629

2021-11-18 16:31 UTC, mattbsox approved these changes

2021-11-18 18:10 UTC, cherylking requested changes

2021-11-18 18:10 UTC, cherylking commented on src/main/groovy/io/openliberty/tools/gradle/Liberty.groovy
> +        if (project.hasProperty('liberty.installDir')) {
Two things...I think we should call `checkAndAppendWlp(project)` here...and that method needs updating to look for the property before using `project.liberty.installDir`.  Or make a second `checkAndAppendWlp(String)` and pass in the path to check.

2021-11-18 18:10 UTC, cherylking commented on src/test/groovy/io/openliberty/tools/gradle/InstallLiberty_installDir_missing_wlp_Test.groovy
> +            .withArguments('installLiberty', '-Pliberty.installDir=installDir-valid-install/build/wlp', '-i', '-s')
After adding the logic to check the path above, you can add another test here to pass in a path with `-Pliberty.installDir` that does not end with `/wlp`.

2021-11-18 21:55 UTC, cherylking approved these changes

2021-11-19 14:06 UTC, cherylking commented on docs/libertyExtensions.md
> +| installDir | String | 1.0 | Path to the WebSphere Liberty server installation `wlp` directory. To use a pre-installed version of Liberty, set this property to the path of the Liberty `wlp` director
I don't think I would put `{wlp}` in the example, and let's remove the break.

2021-11-19 14:09 UTC, cherylking commented on docs/libertyExtensions.md
> +| installDir | String | 1.0 | Path to the WebSphere Liberty server installation `wlp` directory. To use a pre-installed version of Liberty, set this property to the path of the Liberty `wlp` director
Also, installLiberty.md might be a good place to show an example usage of the installDir property. That is where the `runtime` properties for specifying groupId, artifactId and version for the Liberty runtime are discussed in more detail.

2021-11-19 17:06 UTC, cherylking approved these changes

2021-11-19 21:12 UTC, merged