Update documentation for generateFeatures task
OpenLiberty/ci.gradle pull request #754
Opened 2022-05-26 16:19 UTC by kathrynkodama

See https://github.com/OpenLiberty/ci.maven/pull/1522 for the same documentation updates in ci.maven

Signed-off-by: Kathryn Kodama <kathryn.s.kodama@gmail.com>

2022-05-26 18:42 UTC, turkeylurkey approved these changes
I'd like to suggest not reformatting too much because it can make the differences hard to find.

2022-05-26 18:47 UTC, TrevCraw approved these changes

2022-05-26 21:22 UTC, TrevCraw requested changes

2022-05-26 21:22 UTC, TrevCraw commented on docs/generateFeatures.md
> +If you are using [devc](libertyDev.md#libertydevc-task-container-mode), ensure that the `generated-features.xml` configuration file is copied via your Dockerfile.
```suggestion
If you are using [devc](libertyDev.md#libertydevc-task-container-mode), ensure that the `generated-features.xml` configuration file is copied to your Docker image via your Dockerfile.
```

2022-05-26 21:22 UTC, TrevCraw commented on docs/libertyDev.md
> +N.B. starting in 3.4, dev mode invokes `generate-features`. Ensure that the `generated-features.xml` configuration file is copied via your Dockerfile.
```suggestion
N.B. starting in 3.4, dev mode invokes `generate-features`. Ensure that the `generated-features.xml` configuration file is copied to your Docker image via your Dockerfile.
```

2022-05-26 21:22 UTC, TrevCraw commented on docs/generateFeatures.md
> +For example, if you have the following Jakarta EE and MicroProfile dependencies in your `build.gradle` file, features compatible with Jakarta EE `8.0` and MicroProfile `4.1` will be generated.
```suggestion
For example, if you have the following Jakarta EE and MicroProfile dependencies in your `build.gradle` file, features compatible with Jakarta EE `8.0.0` and MicroProfile `4.1` will be generated.
```

2022-05-26 21:22 UTC, TrevCraw commented on docs/generateFeatures.md
> +For Jakarta EE API, this task looks for `jakarta:jakartaee-api` dependency with version `8.0`.
```suggestion
For Jakarta EE API, this task looks for `jakarta:jakartaee-api` dependency with version `8.0.0`.
```

2022-05-26 21:35 UTC, turkeylurkey commented on docs/generateFeatures.md
> +COPY --chown=1001:0  build/wlp/usr/servers/defaultServer/configDropins/overrides/generated-features.xml /config/configDropins/overrides/
Suggestion: another sample COPY for Linux that copies the whole `overrides` dir.

2022-05-26 21:35 UTC, turkeylurkey approved these changes

2022-05-27 17:50 UTC, TrevCraw approved these changes

2022-05-27 17:53 UTC, merged