copy user feature esa
OpenLiberty/ci.gradle pull request #817
Opened 2023-05-02 19:40 UTC by jjiwooLim

2023-05-04 14:21 UTC, cherylking commented
@jjiwooLim You might want to merge the latest main into your branch, as I made a couple changes to test cases that are failing often lately. Hopefully it will help turn more of the builds green.

2023-05-08 16:49 UTC, cherylking requested changes

2023-05-08 16:49 UTC, cherylking commented on src/main/groovy/io/openliberty/tools/gradle/tasks/InstallFeatureTask.groovy
> +		boolean isClosedLiberty = false;
Update copyright year to 2023.

2023-05-08 20:00 UTC, jjiwooLim commented
removed yaml changes

2023-05-08 20:01 UTC, cherylking approved these changes

2023-05-08 22:16 UTC, merged