multiple server restart issue fix for maven. adding constructor para…
OpenLiberty/ci.gradle pull request #927
Opened 2024-12-23 04:45 UTC by arunvenmany-ibm

…meter with true for ci.gradle

2024-12-23 05:05 UTC, arunvenmany-ibm commented
Application multi restart is reported in Maven, Gradle has build state check, which will not trigger recompile, unless there is any file change.
We are passing flag as "true" to trigger the recompile logic always, and let gradle handle the dirty check

2025-01-08 17:50 UTC, cherylking requested changes

2025-01-08 17:50 UTC, cherylking commented on src/main/groovy/io/openliberty/tools/gradle/tasks/DevTask.groovy
> +                    ,Collections.emptyMap() /*ignored for gradle*/
This PR would be unnecessary if you provided a constructor that did not take this new Map since it is not needed for Gradle. That constructor could then just turn around and call the other one passing an empty Map, but in ci.common instead of ci.gradle.

2025-01-09 08:18 UTC, arunvenmany-ibm commented
Closing PR after adding a new constructor in ci.common DevUtil() for ci.maven, hence common changes will not affect ci.gradle

2025-01-09 08:18 UTC, closed without merging